name: docs
on:
  push:
    branches:
      - miss
permissions:
  contents: read
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.10'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install autodocsumm
        pip install sphinx-rtd-theme
        pip install setuptools
        pip install scikit-learn==1.5.2
        pip install bnlearn==0.10.2
        pip install networkx==3.4.2
        pip install matplotlib==3.9.2
        pip install pgmpy==0.1.26
        pip install numpy==1.26.4
        pip install pandas==2.2.3
        pip install scipy==1.11.4
        pip install statsmodels==0.14.4

     
     
    - name: Build docs
      run: |
        cd docs
        make html
        mv build _build
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.TOKEN  }}
        publish_dir: docs/_build/html/