name: docs
on:
  push:
    branches:
      - main
permissions:
  contents: read
jobs:
  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11.10'

    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install sphinx
        pip install autodocsumm
        pip install sphinx-rtd-theme
        pip install setuptools
        pip install scikit-learn==1.0.2
        pip install bnlearn
        pip install networkx==2.8.8
        pip install matplotlib==3.6.2
        pip install pgmpy==0.1.20
        pip install numpy==1.23.4
        pip install pandas==1.5.1
        pip install scipy==1.9.3
        pip install statsmodels==0.13.5
     
    - name: Build docs
      run: |
        cd docs
        make html
        mv build _build
    # https://github.com/peaceiris/actions-gh-pages
    - name: Deploy
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.TOKEN  }}
        publish_dir: docs/_build/html/